package:
  name: pandas-taj
  version: {{ environ.get("GIT_DESCRIBE_TAG") }}+{{ environ.get("GIT_DESCRIBE_NUMBER") }}

source:
  git_url: ../
  git_tag: HEAD

requirements:
  build:
    - python
    - setuptools
    - pandas
    - cython

  run:
    - python
    - pandas
    - cython

test:
  requires:
    - pytest
    - cython
    - pandas
  imports:
    - taj
