package:
  name: pandas-taj
  version: 0.1

#source:
#  path: ../

#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pandas

  run:
    - python
    - pandas

test:
  requires:
    - pytest
  imports:
    - taj
