package:
  name: pandas-taj
  version: {{ environ.get("GIT_DESCRIBE_TAG") }} + {{ environ.get("GIT_DESCRIBE_NUMBER") }}

source:
  git_url: ../
  git_tag: HEAD

#build:
#  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pandas

  run:
    - python
    - pandas

test:
  requires:
    - pytest
  imports:
    - taj
